import React from "react";
import "./body.css";

function Body() {
  return (
    <div className="body">
      <h4
        style={{
          fontSize: "28px",
          textAlign: "left",
          paddingLeft: "100px",
          paddingTop: "50px",
        }}
        class="text-left"
      >
        Home/Writing Assistant
      </h4>
      <h4
        style={{
          fontSize: "18px",
          textAlign: "left",
          paddingLeft: "100px",
          paddingTop: "20px",
        }}
      >
        Enter Input to get{" "}
        <span style={{ color: "blue" }}>Writing Assistant</span>
      </h4>
      <div style={{ textAlign: "left", paddingLeft: "120px" }} className="row">
        <div className="inline">
          <div class="row-auto my-1">
            <label
              style={{ paddingRight: "15px" }}
              class="my-1 mr-2"
              for="inlineFormCustomSelectPref"
            >
              word count:
            </label>
            <select
              style={{ height: "44px", width: "60x" }}
              class="custom-select my-1 mr-sm-2"
              id="inlineFormCustomSelectPref"
            >
              <option selected>0</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </select>

            <label
              style={{ paddingRight: "15px", paddingLeft: "30px" }}
              class="my-1 mr-2"
              for="inlineFormCustomSelectPref"
            >
              Prompt:
            </label>
            <select
              style={{ height: "44px", width: "60x" }}
              class="custom-select my-1 mr-sm-2"
              id="inlineFormCustomSelectPref"
            >
              <option selected>select</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </select>

            <label
              style={{ paddingRight: "20px", paddingLeft: "30px" }}
              class="my-1 mr-2"
              for="inlineFormCustomSelectPref"
            >
              Creativity:
            </label>
            <select
              style={{ height: "44px", width: "60x" }}
              class="custom-select my-1 mr-sm-2"
              id="inlineFormCustomSelectPref"
            >
              <option selected>select</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </select>
          </div>
        </div>
      </div>


      

      <div style={{ position: "absolute", right: "200px", top: "120px" }}>
        <div>
          <button
            style={{ position: "absolute", right: "150px", width: "100px" }}
            type="button"
            class="btn btn-primary"
          >
            Save
          </button>
          <button
            style={{ position: "absolute", right: "10px", width: "100px" }}
            type="button"
            class="btn btn-primary"
          >
            Filter
          </button>
        </div>
        <div style={{ paddingTop: "100px" }}>
          <button
            style={{ paddintTop: "100px", width: "300px" }}
            type="button"
            class="btn btn-primary"
          >
            write for me
          </button>
        </div>
        <div style={{paddingTop:"12px"}}>
          <div class="card" style={{width:"400px"}}>
            <div style={{display:"flex"}} class="card-body">
              <p style={{marginTop:"20px", marginRight:"8px"}} class="card-text">
                Copy
              </p>
              <div class="vr"></div>
              <p style={{paddingLeft:"15px", textAlign:"left", height:"70px", fontSize:"10px"}} class="card-text">
              As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.
              </p>
            </div>
          </div>
        </div>


        <div style={{paddingTop:"12px"}}>
          <div class="card" style={{width:"400px"}}>
            <div style={{display:"flex"}} class="card-body">
              <p style={{marginTop:"20px", marginRight:"8px"}} class="card-text">
                Copy
              </p>
              <div class="vr"></div>
              <p style={{paddingLeft:"15px", textAlign:"left", height:"70px", fontSize:"10px"}} class="card-text">
              As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.
              </p>
            </div>
          </div>
        </div>


        <div style={{paddingTop:"12px"}}>
          <div class="card" style={{width:"400px"}}>
            <div style={{display:"flex"}} class="card-body">
              <p style={{marginTop:"20px", marginRight:"8px"}} class="card-text">
                Copy
              </p>
              <div class="vr"></div>
              <p style={{paddingLeft:"15px", textAlign:"left", height:"70px", fontSize:"10px"}} class="card-text">
              As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.
              </p>
            </div>
          </div>
        </div>

      </div>

      <div class="text-box">
        <input
          style={{
            width: "600px",
            height: "400px",
            position: "absolute",
            left: "225px",
            paddingTop: "100px",
          }}
        ></input>
      </div>
      
    </div>
  );
}

export default Body;
